name: build

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Monologue
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
      - name: install wine
        id: wine_install
        run: |
          sudo apt-get update
          sudo apt install wine64
          echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT
      - name: export game
        id: export
        uses: firebelley/godot-export@v5.1.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_export_templates.tpz
          relative_project_path: ./ # build the standard project
          relative_export_path: ./build/ # move export output to this directory relative to git root
          wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}
      - name: create release
        uses: actions/upload-artifact@v3
        with:
          name: Monologue ${{ github.event.pull_request.title }}
          path: ${{ steps.export.outputs.build_directory }}
          if-no-files-found: error